package com.pawlowski.sportnite.presentation.view_models_related.full_screen_list_screen

import org.orbitmvi.orbit.ContainerHost

interface IFullScreenListViewModel: ContainerHost<FullScreenListUiState, FullScreenListSideEffect>