package com.pawlowski.sportnite.presentation.view_models_related.account_details_screen

import org.orbitmvi.orbit.ContainerHost

interface IAccountDetailsScreenViewModel: ContainerHost<AccountDetailsScreenUiState, AccountDetailsScreenSideEffect> {
}